/**
 * Guest list used to generate personalized invitation links (?to=<name>).
 * Order is preserved from the source list provided by the couple.
 */
export const GUEST_NAMES: string[] = [
  "Dona",
  "Mbak Ifa",
  "Mbak Aqilla",
  "Firda",
  "Zuliana",
  "Mb Sukma",
  "Mb Siska",
  "Takim",
  "Mas Yosa",
  "Aan",
  "Amru",
  "Yayuk",
  "Dimas Pantai",
  "Elvira",
  "Ella Poreng",
  "Fendy",
  "Ica",
  "Ratih",
  "Ines Sandi",
  "Kak Nopan",
  "Kurnia",
  "Lena",
  "Mb Dian STCA",
  "Puput Gembul",
  "Wulan STCA",
  "Mira",
  "Mbak Endang",
  "Mbak Umi",
  "Mbak Friska Ayu",
  "Mbak Ince",
  "Mbak Laras",
  "Mbak Putri Urecel",
  "Mbak Tania",
  "Mbak Wulan",
  "Mutiara",
  "Mbak Nik",
  "Sauqi",
  "Mita",
  "Thea",
  "Theo",
  "Tia",
  "Tika Yulia",
  "Bagas",
  "Rizky Cucok",
  "Christian Vikri",
  "Yanti",
  "Yani",
  "Zaenal",
  "Mas Tintus",
  "Lintang",
  "Amelia & Koko",
  "Ririn",
  "Mba Pingky",
  "Novita",
  "Revin",
  "Otong",
  "Dek Mira",
  "Mbak Etik & Mas Findi",
  "Mbak Sukma & Mas Geo",
  "Moren",
  "Sherly & Mas Yoga",
  "Monika",
  "Mbak Ocak",
  "Om Chandra & Tante Nana",
  "Puspita",
  "Mas Biel",
  "Mas Crison",
  "Om Yeskiel",
  "Ipe",
  "Mas Candra",
  "Febri",
  "Elsa",
  "Om Sukma",
  "Ajeng",
  "Mb Eris",
  "Mbak Ella",
  "Alpu",
  "Mb Emi URCL",
  "Viranita",
  "Lia URC",
  "Ceceng",
  "Tante Tia",
  "Merlin",
  "Desyta",
  "Hanny",
  "Albet",
  "Andreas",
  "Dimas",
  "Mbak Nila",
  "Lois",
  "Holly",
  "Mb Rosa",
  "Aima",
  "Eka",
  "Mas Heksa",
  "Jea",
  "Mbak Sinta Purba",
  "Sheilla",
  "Mbak Thesa & Mbak Vasya",
  "Citra",

  "Sherly BN",
  "Wulan BN",
  "Budi BN",
  "Nurlina BN",
  "Aima BN",
  "Dhegih BN",
  "Natan BN",
  "Richi Yoga BN",
  "Yusnia BN",
  "Jhosef BN",
  "Priskilla BN",
  "Dewi BN",
  "Kak Yunita & Partner BN",
  "Kak Hena BN",
  "Kak Hani BN",
  "Kak Yoan BN",
  "Consil BN",
  "Davit Kopat BN",
  "Novi PS BN",
  "Jasmine BN",
  "Nopi Lotong BN",
  "Putri Jenang BN",
  "Fanny & Partner BN",
  "Sesel & Gross BN",
  "Kak Mila BN",
  "Kak Tania BN",
  "Kak Ine BN",
  "Aya & Partner BN",
  "Steven BN",
  "Kak Ponco BN",
  "Kak Gigih BN",
  "Olop BN",
  "Kak Desinta BN",
  "Natasya BN",
  "Yabes BN",
  "Nicolas Edo BN",
  "Fery BN",
  "Amanda Eka BN",
  "Yoengky BN",
  "Pedro BN",
  "Mikha BN",
  "Zefanya BN",
  "Jesica Intan BN",
  "Cicilia BN",
  "Ropiah BN",
  "Edcanrim BN",
  "Ozi BN",
  "Novinda BN",
  "Mas Tio BN",
  "Bu Lia & Pak Yafet BN",
  "Absalom BN",
  "Emil BN",
  "Vena BN",
  "Yosua BN",
  "Sugiyanto BN",

  "Pak Badar",
  "Pak Dwi",
  "Pak Ray",
  "Mas Atok",
  "Bre Suma",
  "Akmal Jawsund",
  "Natasya",
  "Mas Naufal",
  "Febi",
  "Davina",
  "Farah",
  "Mas Kahfi",
  "Mas Hakim",
  "Umira",
  "Azhar",
  "Mas Alko",
  "Wawad",
  "Jovan",
  "Dus",
  "Willy",
  "Ko Jendi",
  "Bu Julia",
  "Mas Dani",
  "Tama",

  "Mas Ian",
  "Elang Maulana",
  "Yakub",
  "Yoga",
];
